name: CI-ML-Pipeline

# Déclencheurs du workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Étape 2 : Setup Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader stopwords punkt wordnet

      # Étape 4 : Exécuter le pipeline Data + ML
      - name: Run Data and ML Pipeline
        run: |
          python src/load_data.py
          python src/preprocess.py
          python src/train.py
          python src/evaluate.py

      # Étape 5 : Sauvegarder les résultats MLflow comme artefact
      - name: Upload MLflow results
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: mlruns/
